version: '3'
services: 
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'codibly'
        volumes:
            - dbVol:/var/lib/mysql2 
        ports:
            - 3306
    web:
        build: 
            context: ./API-DB
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8888:8080"
        expose:
            - 8888
        command: ["./wait-for-it.sh", "db:3306", "--", "node", "server.js"]       
volumes:
    dbVol:

